name: Deploy to RunPod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.RUNPOD_PRIVATE_KEY }}

      - name: Deploy to RunPod
        run: |
          ssh -o StrictHostKeyChecking=no user@runpod-server "cd /stable-fiffusion-runpod && git pull && deploy-commands"
