name: Deploy to RunPod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH for RunPod Access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RUNPOD_PRIVATE_KEY }}

    - name: Clone or update project on RunPod
      run: |
        ssh -o StrictHostKeyChecking=no root@213.173.108.202 -p 15539 << EOF
        # Define the project path
        PROJECT_PATH="/root/shopify-runpod-model"

        if [ -d "\$PROJECT_PATH" ]; then
          echo "Project directory exists. Pulling latest changes."
          cd \$PROJECT_PATH && git pull
        else
          echo "Project directory does not exist. Cloning the repository."
          # Using HTTPS to clone the repository
          git clone https://github.com/Patbogbear/shopify-runpod-model.git \$PROJECT_PATH
        fi
        EOF

    - name: Execute scripts on RunPod
      run: |
        ssh -o StrictHostKeyChecking=no root@213.173.102.224 -p 10657 << EOF
        cd /root/shopify-runpod-model

        if [ -f "./install.sh" ]; then
          echo "Running install.sh"
          chmod +x ./install.sh
          ./install.sh
        else
          echo "install.sh does not exist."
        fi

        if [ -f "./launch_sd.sh" ]; then
          echo "Running launch_sd.sh"
          chmod +x ./launch_sd.sh
          ./launch_sd.sh
        else
          echo "launch_sd.sh does not exist."
        fi
        EOF
